import Button from "../components/UI/Button/Button";

const Home = () => {
  return ( <div>
    Home
    <Button action={()=>alert('hello')}>Alert</Button>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus ratione quia repellat cum quod, molestiae quos, amet maiores unde, dignissimos dolor ipsam sunt nihil deserunt optio expedita fuga perspiciatis obcaecati numquam? Cupiditate perferendis quibusdam facere atque assumenda deleniti cum eum est, maiores expedita, consequuntur cumque, repudiandae accusamus modi omnis dicta officia possimus aliquam laboriosam molestiae quidem! Odit nihil illo pariatur temporibus ex? Similique veritatis ratione officiis expedita quo eveniet dicta a aliquid harum repellat ex, nesciunt, assumenda quibusdam aperiam vel voluptatem molestiae earum ea quis enim? Ipsa quae aut necessitatibus placeat nobis voluptate nulla illo? Eligendi quis ea cumque odio!
    Voluptatibus consectetur veniam repellendus nisi dignissimos consequatur dolores labore praesentium natus magnam nobis explicabo, modi nam animi ea optio, nesciunt doloremque quibusdam. Quam, nulla. Vel, exercitationem quam temporibus omnis corporis ratione necessitatibus sint quod dicta accusantium, voluptatibus nostrum! Enim provident dolorum repudiandae! Rerum repellendus assumenda culpa dolor alias porro sunt cumque architecto quas sit quasi dolores modi sint nobis eligendi iure tempora inventore harum, distinctio voluptatum! Nostrum obcaecati eligendi vel! Possimus voluptate nam, nemo nostrum natus harum voluptatum blanditiis consequuntur, perferendis assumenda et tempora exercitationem quam, tenetur id iure aspernatur? Error impedit laborum omnis quidem autem saepe quam itaque ex.
    Quidem fugiat praesentium totam sequi similique, aspernatur officia ab enim soluta quas fugit. Eos, quisquam veritatis. Saepe omnis nulla quibusdam beatae iste repudiandae alias optio minima. Adipisci, maxime veritatis. Nam necessitatibus nemo deserunt odio mollitia consequatur, dignissimos cumque est, blanditiis perferendis quia totam! Odit, cumque impedit explicabo et quasi labore maxime. Est delectus cum quia recusandae veniam ipsa architecto earum temporibus assumenda ullam vero labore aut illum, dolores asperiores molestias fuga minima illo vel voluptatem sequi laudantium suscipit soluta. Maxime animi, provident sed corporis nam eaque molestiae autem quae neque, ducimus tempore. Perferendis corporis enim ex quisquam distinctio, id labore?
    Voluptate minus atque dicta fugit soluta delectus sed aliquid ab tempora veniam, sit repellat. Veniam voluptatum, nesciunt voluptatem dolore illum nihil at tenetur, quisquam rem alias quis eum, facere aliquid soluta aperiam dolorum obcaecati quas ipsa repellendus a numquam iusto vero! Modi tempore, ab nobis voluptatibus quasi eaque odit quos asperiores. Maiores porro libero reprehenderit repellendus! Exercitationem porro illum iure ipsa laboriosam? Assumenda quae natus eligendi repellat quasi. Exercitationem dolorem ullam ipsam, qui ipsa illo blanditiis expedita voluptate quia. Molestias velit modi cumque aut, id eos error quod enim nesciunt. Alias maiores eaque vero autem consequuntur placeat incidunt optio velit.
    Voluptatum quod laudantium cupiditate mollitia tempora quidem sunt molestias ipsa porro sapiente aut beatae molestiae eius nulla unde excepturi sit quos similique dolores veritatis magni, vel odio aliquam? Ut, magnam. Esse delectus nobis adipisci molestias magnam, consequatur minus fugit corrupti cum voluptas dolorem possimus cupiditate ab, ipsum ad nisi ullam mollitia obcaecati quam autem. Eveniet natus qui, possimus hic eaque doloremque rem repudiandae tempore aspernatur impedit sit consectetur necessitatibus voluptatem doloribus voluptas. Officia, beatae repellendus? Reiciendis, recusandae vel beatae eius odit illo est nemo quidem, possimus quod et id dolor. Temporibus, corporis reprehenderit officia voluptatum cum eum quisquam. Optio, pariatur?
    Beatae fugit, rerum necessitatibus explicabo tenetur ipsum perferendis? Accusantium minus quasi voluptatem officiis corporis totam, quis cumque, facere rem animi suscipit aut eveniet eos sint nesciunt quisquam ullam sed hic ad inventore aperiam reprehenderit pariatur ab autem. Temporibus dignissimos veritatis ut exercitationem iure sit itaque maiores rerum. Deleniti tempora sequi veniam ad ullam nobis, dolorum distinctio, officia, veritatis commodi magni repudiandae molestiae cum eum assumenda. Impedit fuga, architecto et iste ut eos voluptas suscipit nobis ipsum dolorum laboriosam ipsam harum repellat dolor similique pariatur, ipsa non? Sed fuga in officia cupiditate corrupti corporis ea, consequuntur molestias sequi necessitatibus eius odio!
    Tempore possimus ut recusandae pariatur modi. In odio dolorem, vero pariatur ratione ducimus repellat, fuga ab laboriosam cupiditate repellendus excepturi libero! Voluptas illo debitis error quos natus sed animi, quae quas esse sint deserunt quibusdam aut voluptatum atque aperiam sequi minima, incidunt, ipsa harum ratione. Debitis porro eaque distinctio, nihil laudantium nam voluptates omnis vero. Doloremque, beatae? Totam pariatur voluptas consequuntur id cupiditate fugit ex. Magni fugiat odit culpa modi eveniet quisquam facere minima esse blanditiis. Rem adipisci iste delectus molestiae aliquam? Ducimus quis aperiam dicta fuga accusamus libero laudantium repudiandae? Porro officiis ratione, explicabo magnam ex nam rem repellat!
    Tempora perferendis labore commodi voluptatum illum voluptas hic deserunt optio. Ea voluptatum in dolores expedita, officiis nihil rerum placeat consectetur incidunt, dolore dignissimos cumque eius id eos at tempora aperiam modi asperiores odit. Cupiditate, sunt. Natus animi eum error nemo illum unde provident veniam quod culpa, at corrupti consequatur. Expedita deleniti autem hic! Earum nam dicta libero beatae voluptatem exercitationem, adipisci voluptate natus, similique, tempore ad ullam animi ex consequuntur laboriosam dolorem neque. Enim ipsum neque vitae aperiam, quis aspernatur, placeat laboriosam, itaque minima accusantium iste nam beatae obcaecati reprehenderit nisi optio tempora nesciunt blanditiis dolorem culpa non magni cum.
    Nostrum maiores recusandae, nihil sed eius vero culpa nobis, minima quas sunt saepe iure, non sit omnis veritatis incidunt odit commodi placeat voluptas! Nam debitis ea animi vel blanditiis. Illum provident quo quod aspernatur eveniet aperiam laborum dicta hic error dolore fugit impedit tempore nam amet cumque, exercitationem incidunt deserunt iusto eum magnam perferendis illo veritatis dolorem. Nemo nesciunt corporis, deserunt fuga facilis quod esse amet, iste maiores quibusdam adipisci perferendis officia, sint alias quaerat odit. Earum beatae rem odit dicta vel. Nobis totam beatae vitae nostrum. Minus, hic magnam ullam deleniti, placeat nemo nobis perferendis rem neque reiciendis velit.
    Vero eligendi doloribus possimus? Natus voluptas adipisci illum id dolores ab, tempore cupiditate tempora ex doloribus alias quis voluptatibus numquam delectus officia esse dolore accusamus quo in dignissimos maxime et veniam laudantium libero. Doloremque ad facere ducimus tenetur facilis commodi sint consequuntur enim! Debitis tempore a natus optio expedita doloremque quae dolorum qui nostrum quasi quam vel iure corporis obcaecati laboriosam saepe eos, molestiae minima sunt praesentium dolores est adipisci assumenda atque. Consequatur et qui voluptatibus fuga exercitationem nulla illo debitis consequuntur cupiditate repudiandae deleniti pariatur esse nihil quaerat dolorem non ullam veritatis magnam distinctio veniam, molestias voluptatum laudantium ipsa!
  </div> );
}
 
export default Home;